services:
    web:
        container_name: reminder_bot
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "8080:80"  # Map port 8080 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - reminder_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - reminder-network  # Connect to the custom network
    reminder_app:
        container_name: reminder_app
        build: .  # Build from the Dockerfile
        depends_on:
            - reminder_db
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
        networks:
            - reminder-network  # Connect to the custom network

    reminder_db:
        container_name: reminder_db
        image: mysql:8  # Use MySQL image
        restart: always
        ports:
            - "3301:3306"
        environment:
            MYSQL_DATABASE: reminder_db  # Create a database named 'laravel'
            MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
        volumes:
            - reminder_db:/var/lib/mysql  # Persist MySQL data
        networks:
            - reminder-network  # Connect to the custom network

    reminder_node:
        container_name: reminder_node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - reminder-network
        command: bash -c "npm install && npm run build"

# Define the custom network
networks:
    reminder-network:  # Create a custom network named 'laravel-network'
        driver: bridge

# Define the volume for MySQL data persistence
volumes:
    reminder_db:
